import localFont from "next/font/local";
import "./globals.css";
import { DarkModeProvider } from '../context/DarkModeContext'; 
import DarkModeToggle from '../components/DarkModeToggle'; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <DarkModeProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="flex justify-between p-4">
            <h1>Movie App</h1>
            <DarkModeToggle />
          </div>
          {children}
        </body>
      </DarkModeProvider>
    </html>
  );
}
